name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check DOCKER_USERNAME
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME is EMPTY"
            exit 1
          else
            echo "DOCKER_USERNAME is PRESENT"
          fi

      - name: Check DOCKER_PASSWORD
        run: |
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DOCKER_PASSWORD is EMPTY"
            exit 1
          else
            echo "DOCKER_PASSWORD is PRESENT"
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nareshnagar234/devops-cicd-demo:latest